import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'
import { ADMIN } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'users',
        path: '',
        title: 'Users',
        translateKey: 'nav.users.users',
        icon: 'users',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'users.allProviders',
                path: '/users/providers',
                title: 'All Providers',
                translateKey: 'nav.users.allProviders',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'users.allClients',
                path: '/users/clients',
                title: 'All Clients',
                translateKey: 'nav.users.allClients',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'handyMan',
        path: '',
        title: 'HandyMan',
        translateKey: 'nav.handyMan.handyMan',
        icon: 'handyMan',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'handyMan.messages',
                path: '/handy-man/messages',
                title: 'Messages/Enquiries',
                translateKey: 'nav.handyMan.messages',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'handyMan.activeBookings',
                path: '/handy-man/active-bookings',
                title: 'Active Bookings',
                translateKey: 'nav.handyMan.activeBookings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'handyMan.completedBookings',
                path: '/handy-man/completed-bookings',
                title: 'Completed Bookings',
                translateKey: 'nav.handyMan.completedBookings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'handyMan.inDispute',
                path: '/handy-man/bookings-in-dispute',
                title: 'Bookings in Dispute',
                translateKey: 'nav.handyMan.inDispute',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'finance',
        path: '',
        title: 'Finance',
        translateKey: 'nav.finance.finance',
        icon: 'finance',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'finance.deposits',
                path: '/finance/deposits',
                title: 'Deposits',
                translateKey: 'nav.finance.deposits',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'finance.billPayments',
                path: '/finance/bill-payments',
                title: 'Bill Payments',
                translateKey: 'nav.finance.billPayments',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'finance.servicePayments',
                path: '/finance/service-payments',
                title: 'Service Payments',
                translateKey: 'nav.finance.servicePayments',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'finance.referralRewards',
                path: '/finance/referral-rewards',
                title: 'Referral Rewards',
                translateKey: 'nav.finance.referralRewards',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'finance.withdrawals',
                path: '/finance/withdrawals',
                title: 'withdrawals',
                translateKey: 'nav.finance.withdrawals',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'finance.systemCommissions',
                path: '/finance/system-commissions',
                title: 'System Commissions',
                translateKey: 'nav.finance.systemCommissions',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'kyc',
        path: '',
        title: 'KYC Verifications',
        translateKey: 'nav.kyc.kyc',
        icon: 'kyc',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'kyc.pending',
                path: '/kyc/pending',
                title: 'Pending',
                translateKey: 'nav.kyc.pending',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'kyc.rejections',
                path: '/kyc/rejections',
                title: 'Rejections',
                translateKey: 'nav.kyc.rejections',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'system',
        path: '',
        title: 'System Configurations',
        translateKey: 'nav.system.system',
        icon: 'system',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'system.serviceCategories',
                path: '/configurations/service-categories',
                title: 'Service Categories',
                translateKey: 'nav.system.serviceCategories',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'system.referralSettings',
                path: '/configurations/referral-settings',
                title: 'Referral Settings',
                translateKey: 'nav.system.referralSettings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'system.commissionSettings',
                path: '/configurations/commission-settings',
                title: 'Commission Settings',
                translateKey: 'nav.system.commissionSettings',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
